---

all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
  hosts:
    master:
       ansible_host: 192.168.56.10
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    node1:
      ansible_host: 192.168.56.11
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    node2:
      ansible_host: 192.168.56.12
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
