---

all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    #ansible_user: vagrant
    ansible_connection: ssh 
    ansible_ssh_user: vagrant 
    # ansible_ssh_pass: odellya!!2023

  hosts:
    master:
       ansible_host: 192.168.99.11
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    node1:
      ansible_host: 192.168.99.12
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    node2:
      ansible_host: 192.168.99.13
      #ansible_user: vagrant
      #ansible_password: odellya!!2023
      #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
